import type { Metadata } from 'next';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { buildLanguageAlternates } from '@/lib/seo';
import type { Language } from '@/types';

type TermsPageProps = {
  searchParams: Promise<{ lang?: string }>;
};

function normalizeLang(lang?: string): Language {
  return lang === 'ko' || lang === 'ja' || lang === 'es' || lang === 'pt' ? lang : 'en';
}

export const metadata: Metadata = {
  title: 'Terms',
  description: 'Basic terms of service for this website.',
  alternates: {
    canonical: '/terms',
    languages: buildLanguageAlternates('/terms'),
  },
};

const CONTENT: Record<Language, { title: string; subtitle: string; items: string[] }> = {
  en: {
    title: 'Terms of Service',
    subtitle: 'Basic terms for using this website.',
    items: [
      'Users are responsible for how they use the outputs generated by this service.',
      'The service may be changed, suspended, or updated without prior notice.',
      'This service does not provide medical diagnosis or legal advice.',
    ],
  },
  ko: {
    title: '이용약관',
    subtitle: '본 웹사이트 이용을 위한 기본 약관입니다.',
    items: [
      '사용자는 본 서비스의 결과물을 활용하는 방식에 대해 스스로 책임을 집니다.',
      '서비스는 사전 고지 없이 변경, 중단 또는 업데이트될 수 있습니다.',
      '본 서비스는 의료 진단이나 법률 자문을 제공하지 않습니다.',
    ],
  },
  ja: {
    title: '利用規約',
    subtitle: '本ウェブサイト利用のための基本規約です。',
    items: [
      '本サービスの出力の利用方法については、利用者自身が責任を負います。',
      'サービスは事前通知なく変更・中断・更新される場合があります。',
      '本サービスは医療診断や法律助言を提供するものではありません。',
    ],
  },
  es: {
    title: 'Terminos de Servicio',
    subtitle: 'Terminos basicos para usar este sitio web.',
    items: [
      'El usuario es responsable del uso que haga de los resultados generados por este servicio.',
      'El servicio puede cambiarse, suspenderse o actualizarse sin aviso previo.',
      'Este servicio no proporciona diagnostico medico ni asesoria legal.',
    ],
  },
  pt: {
    title: 'Termos de Servico',
    subtitle: 'Termos basicos para usar este site.',
    items: [
      'O usuario e responsavel por como utiliza os resultados gerados por este servico.',
      'O servico pode ser alterado, suspenso ou atualizado sem aviso previo.',
      'Este servico nao fornece diagnostico medico nem consultoria juridica.',
    ],
  },
};

export default async function TermsPage({ searchParams }: TermsPageProps) {
  const { lang } = await searchParams;
  const activeLang = normalizeLang(lang);
  const content = CONTENT[activeLang];

  return (
    <div className="min-h-screen bg-[#F7F9FB]">
      <Header />
      <main className="mx-auto max-w-7xl px-4 pb-10 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl rounded-lg border border-slate-200 bg-white p-6">
          <h1 className="text-3xl font-bold text-slate-900">{content.title}</h1>
          <p className="mt-3 text-slate-600">{content.subtitle}</p>
          <ul className="mt-6 space-y-3 text-slate-700">
            {content.items.map((item) => (
              <li key={item} className="rounded-md bg-slate-50 px-4 py-3">
                {item}
              </li>
            ))}
          </ul>
        </div>
      </main>
      <Footer />
    </div>
  );
}
